#!/usr/bin/env python3
"""Reusable Graph-RAG memory, dossier, and proposal helpers."""

from __future__ import annotations

import json
import re
from collections import defaultdict
from typing import Any
from urllib.parse import urlparse

from pipeline_common import (
    PROPOSAL_LEDGER_FILE,
    append_jsonl,
    compact_summary,
    iso_now,
    load_entity_alias_index,
    load_json,
    load_publication_ledger,
    normalize_text,
    relation_label_ru,
    resolve_entity,
    short_host,
    stable_hash,
)


PROFILE_NOISE_PATTERNS = (
    "appears in the graph",
    "tracked in the graph as",
    "structured graph context",
    "known public links",
    "auto-generated by actor-pair research",
    "auto generated by actor pair research",
    "appears in the armenia graph",
    "graph context",
)

PERSON_REL_TYPES = {"holds_office_in", "member_of", "aligned_with", "leads", "board_member_of", "owns_or_controls"}
OBJECT_REL_TYPES = {"holds_office_in", "member_of", "aligned_with", "leads", "board_member_of", "owns_or_controls", "licensed_by", "funded_by", "contracted_with_state", "implemented_by"}
DURABLE_REL_TYPES = {
    "holds_office_in",
    "member_of",
    "aligned_with",
    "leads",
    "board_member_of",
    "owns_or_controls",
    "licensed_by",
    "funded_by",
    "contracted_with_state",
    "implemented_by",
    "affects",
    "announced_by",
}
EPISODIC_REL_TYPES = {
    "mentions",
    "reported_by",
    "watchdog_allegation",
    "media_claim_disputed",
    "criticized_by",
    "subject_of_legal_case",
    "investigated_by",
}
OBJECT_EVENT_REL_TYPES = {
    "subject_of_legal_case",
    "watchdog_allegation",
    "media_claim_disputed",
    "criticized_by",
    "investigated_by",
    "affects",
    "announced_by",
    "publicly_supported",
    "publicly_opposed",
}


def _collapse_repeated_text(text: str) -> str:
    cleaned = str(text or "").strip()
    if not cleaned:
        return ""
    words = cleaned.split()
    if len(words) >= 6 and len(words) % 2 == 0:
        half = len(words) // 2
        if " ".join(words[:half]) == " ".join(words[half:]):
            cleaned = " ".join(words[:half])
            words = cleaned.split()
    sentence_parts = [part.strip(" .;,-") for part in re.split(r"[.!?]+", cleaned) if part.strip(" .;,-")]
    unique_sentences: list[str] = []
    for part in sentence_parts:
        lowered = normalize_text(part)
        if lowered and lowered not in {normalize_text(item) for item in unique_sentences}:
            unique_sentences.append(part)
    if unique_sentences:
        cleaned = ". ".join(unique_sentences)
    return cleaned.strip(" -|,;.")


def _unique_texts(values: list[str], *, limit: int = 8) -> list[str]:
    rows: list[str] = []
    seen: set[str] = set()
    for value in values:
        text = strip_boilerplate(value)
        lowered = normalize_text(text)
        if not text or not lowered or lowered in seen:
            continue
        seen.add(lowered)
        rows.append(text)
        if len(rows) >= limit:
            break
    return rows


def _entity_domains(entity: dict[str, Any]) -> list[str]:
    domains: list[str] = []
    links = entity.get("links", {}) if isinstance(entity.get("links", {}), dict) else {}
    for value in links.values():
        parsed = urlparse(str(value or "").strip())
        host = parsed.netloc.lower().replace("www.", "") if parsed and parsed.netloc else ""
        if host and host not in domains:
            domains.append(host)
    return domains


def _dedupe_source_rows(rows: list[dict[str, Any]], *, limit: int = 12) -> list[dict[str, Any]]:
    result: list[dict[str, Any]] = []
    seen: set[tuple[str, str]] = set()
    for row in rows:
        if not isinstance(row, dict):
            continue
        url = str(row.get("url") or "").strip()
        title = normalize_text(str(row.get("title") or row.get("label") or row.get("domain") or ""))
        key = (url, title)
        if key in seen:
            continue
        seen.add(key)
        result.append(row)
        if len(result) >= limit:
            break
    return result


def strip_boilerplate(text: str) -> str:
    cleaned = compact_summary(str(text or ""))
    cleaned = re.sub(r"window\.dataLayer.*", " ", cleaned, flags=re.I)
    cleaned = re.sub(r"function\s+gtag\s*\([^)]*\)\s*\{[^}]*\}", " ", cleaned, flags=re.I)
    cleaned = re.sub(r"gtag\s*\([^)]*\)\s*;?", " ", cleaned, flags=re.I)
    cleaned = re.sub(r"eval\s*\(.*", " ", cleaned, flags=re.I)
    cleaned = re.sub(r"\b(key relations|current graph[- ]backed profile|graph[- ]backed profile|structured graph context|known public links)\b.*", " ", cleaned, flags=re.I)
    cleaned = re.sub(r"\s+", " ", cleaned).strip(" -|,;")
    lowered = normalize_text(cleaned)
    for marker in PROFILE_NOISE_PATTERNS:
        lowered = lowered.replace(marker, " ")
    lowered = re.sub(r"\b(key relations|current graph backed profile|graph backed profile)\b.*", " ", lowered, flags=re.I)
    lowered = re.sub(r"\s+", " ", lowered).strip(" -|,;")
    return compact_summary(_collapse_repeated_text(lowered))


def entity_index(graph: dict[str, Any]) -> dict[str, dict[str, Any]]:
    return {
        str(entity.get("id", "")).strip(): entity
        for entity in graph.get("entities", [])
        if isinstance(entity, dict) and str(entity.get("id", "")).strip()
    }


def relation_index(graph: dict[str, Any]) -> dict[str, dict[str, Any]]:
    return {
        str(relation.get("id", "")).strip(): relation
        for relation in graph.get("relations", [])
        if isinstance(relation, dict) and str(relation.get("id", "")).strip()
    }


def entity_kind(entity: dict[str, Any]) -> str:
    category = str(entity.get("category") or "").strip()
    subtype = str(entity.get("subtype") or "").strip()
    if category == "person" or subtype in {"politician", "minister", "deputy", "mayor", "leader", "official"}:
        return "person"
    if subtype in {"office", "law", "case", "media", "company"}:
        return subtype
    if category == "media" or subtype == "source":
        return "media"
    if category in {"institution", "organization", "company", "media", "case", "law", "office"}:
        return category
    if subtype in {"party", "news_outlet"}:
        return subtype
    return category or "unknown"


def canonical_aliases(entity: dict[str, Any], graph: dict[str, Any] | None = None) -> list[str]:
    aliases: list[str] = []
    for alias in [entity.get("name", ""), *(entity.get("aliases", []) or [])]:
        text = str(alias or "").strip()
        if text and text not in aliases:
            aliases.append(text)
    if graph:
        alias_index = load_entity_alias_index(graph)
        for bucket in alias_index.values():
            for alias, entity_id in bucket.items():
                if str(entity_id) == str(entity.get("id")) and alias not in aliases:
                    aliases.append(alias)
    for domain in _entity_domains(entity):
        bare = domain.replace("www.", "")
        for candidate in [bare, bare.split(".")[0] if "." in bare else ""]:
            if candidate and candidate not in aliases:
                aliases.append(candidate)
    return aliases[:12]


def source_link_record(url: str, *, title: str = "", source_type: str = "", language: str = "", date_if_known: str = "") -> dict[str, Any]:
    url = str(url or "").strip()
    parsed = urlparse(url) if url else None
    domain = parsed.netloc.lower() if parsed and parsed.netloc else short_host(url)
    inferred_type = source_type or ("official" if any(marker in domain for marker in ("gov", "parliament", "president", "prime", "court")) else "media")
    return {
        "title": str(title or "").strip() or domain or url,
        "url": url,
        "domain": domain,
        "source_type": inferred_type,
        "language": str(language or "").strip(),
        "date_if_known": str(date_if_known or "").strip(),
    }


def relation_source_link(relation: dict[str, Any]) -> dict[str, Any] | None:
    url = str(relation.get("source_url") or "").strip()
    if not url:
        return None
    return source_link_record(
        url,
        title=str(relation.get("source_title") or relation.get("notes") or relation.get("evidence_quote") or "").strip(),
        source_type=str(relation.get("source_type") or ""),
        date_if_known=str(relation.get("collected_at") or relation.get("last_checked_at") or ""),
    )


def entity_source_links(entity: dict[str, Any]) -> list[dict[str, Any]]:
    links = entity.get("links", {}) if isinstance(entity.get("links", {}), dict) else {}
    result: list[dict[str, Any]] = []
    for label, url in links.items():
        if not str(url or "").strip():
            continue
        result.append(
            source_link_record(
                str(url),
                title=str(label).replace("_", " ").strip(),
                source_type="official" if str(label).lower() in {"official", "officialsite", "homepage", "site"} else "",
            )
        )
    return result


def entity_relations(graph: dict[str, Any], entity_id: str, *, include_events: bool = False) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for relation in graph.get("relations", []):
        left = str(relation.get("from", "")).strip()
        right = str(relation.get("to", "")).strip()
        if entity_id not in {left, right}:
            continue
        if not include_events and (left.startswith("event-") or right.startswith("event-")):
            continue
        rows.append(relation)
    return rows


def relation_sentence(entity_name: str, other_name: str, relation_type: str, outgoing: bool = True) -> str:
    relation_type = str(relation_type or "").strip()
    label = relation_label_ru(relation_type).strip() or relation_type.replace("_", " ")
    if outgoing:
        return f"{entity_name} {label} {other_name}".strip()
    return f"{other_name} {label} {entity_name}".strip()


def event_rows(graph: dict[str, Any], entity_id: str, limit: int = 8) -> list[dict[str, Any]]:
    event_map = {
        str(event.get("id", "")).strip(): event
        for event in graph.get("event_nodes", [])
        if isinstance(event, dict) and str(event.get("id", "")).strip()
    }
    story_by_event = {
        str(item.get("event_id", "")).strip(): item
        for item in graph.get("story_mentions", [])
        if isinstance(item, dict) and str(item.get("event_id", "")).strip()
    }
    rows: list[dict[str, Any]] = []
    seen: set[str] = set()
    for relation in graph.get("relations", []):
        left = str(relation.get("from", "")).strip()
        right = str(relation.get("to", "")).strip()
        event_id = ""
        if left.startswith("event-") and right == entity_id:
            event_id = left
        elif right.startswith("event-") and left == entity_id:
            event_id = right
        if not event_id or event_id in seen:
            continue
        event = event_map.get(event_id, {})
        mention = story_by_event.get(event_id, {})
        rows.append(
            {
                "event_id": event_id,
                "title": strip_boilerplate(event.get("name") or mention.get("title") or relation.get("evidence_quote") or event_id),
                "summary": strip_boilerplate(event.get("summary") or relation.get("evidence_quote") or event.get("notes") or mention.get("title") or ""),
                "date": str(event.get("updated_at") or mention.get("updated_at") or relation.get("updated_at") or relation.get("collected_at") or ""),
                "topic": str(event.get("subtype") or mention.get("topic") or ""),
                "url": relation.get("source_url") or (next((str(url) for url in (event.get("links", {}) or {}).values() if str(url).strip()), "")),
                "relation_type": str(relation.get("relation_type") or ""),
                "source_link": relation_source_link(relation),
            }
        )
        seen.add(event_id)
        if len(rows) >= limit:
            break
    rows.sort(key=lambda row: (str(row.get("date") or ""), str(row.get("title") or "")), reverse=True)
    return rows[:limit]


def _direct_rows(graph: dict[str, Any], entity: dict[str, Any], *, limit: int = 12) -> list[dict[str, Any]]:
    entity_id = str(entity.get("id", "")).strip()
    entities = entity_index(graph)
    rows: list[dict[str, Any]] = []
    seen: set[tuple[str, str]] = set()
    for relation in entity_relations(graph, entity_id, include_events=True):
        relation_type = str(relation.get("relation_type") or "").strip()
        if relation_type not in DURABLE_REL_TYPES | EPISODIC_REL_TYPES | {"mentions"}:
            continue
        left = str(relation.get("from", "")).strip()
        right = str(relation.get("to", "")).strip()
        other_id = right if left == entity_id else left
        sig = (relation_type, other_id)
        if sig in seen:
            continue
        seen.add(sig)
        other = entities.get(other_id, {})
        rows.append(
            {
                "relation_type": relation_type,
                "entity_id": other_id,
                "name": str(other.get("name") or other_id).strip(),
                "entity_type": entity_kind(other) or str(other.get("category") or "unknown"),
                "confidence": round(float(relation.get("confidence", 0.0) or 0.0), 3),
                "layer": str(relation.get("layer") or ("durable" if relation_type in DURABLE_REL_TYPES else "episodic" if relation_type in EPISODIC_REL_TYPES else "inferred")),
                "human_text": strip_boilerplate(relation.get("human_text") or relation.get("notes") or relation.get("evidence_quote") or ""),
                "evidence_quote": strip_boilerplate(relation.get("evidence_quote") or relation.get("notes") or ""),
                "source_link": relation_source_link(relation),
                "provenance": {
                    "relation_id": relation.get("id"),
                    "source_type": relation.get("source_type", ""),
                    "evidence_level": relation.get("evidence_level", ""),
                    "status": relation.get("status", ""),
                },
            }
        )
    rows.sort(key=lambda row: (-float(row.get("confidence", 0.0) or 0.0), str(row.get("name") or "")))
    return rows[:limit]


def _indirect_rows(graph: dict[str, Any], entity: dict[str, Any], direct_rows: list[dict[str, Any]], *, limit: int = 10) -> list[dict[str, Any]]:
    entities = entity_index(graph)
    entity_id = str(entity.get("id", "")).strip()
    hubs = [row["entity_id"] for row in direct_rows if row.get("entity_type") in {"institution", "organization", "company", "media", "case", "law", "office", "event"} or row.get("entity_id", "").startswith(("party-", "institution-", "office-", "event-"))]
    rows: list[dict[str, Any]] = []
    seen: set[tuple[str, str]] = set()
    for hub_id in hubs:
        for relation in entity_relations(graph, hub_id, include_events=True):
            relation_type = str(relation.get("relation_type") or "").strip()
            left = str(relation.get("from", "")).strip()
            right = str(relation.get("to", "")).strip()
            other_id = right if left == hub_id else left
            if other_id in {hub_id, entity_id}:
                continue
            other = entities.get(other_id, {})
            if entity_kind(other) != "person":
                continue
            sig = (hub_id, other_id)
            if sig in seen:
                continue
            seen.add(sig)
            rows.append(
                {
                    "via_id": hub_id,
                    "via_name": str(entities.get(hub_id, {}).get("name") or hub_id),
                    "entity_id": other_id,
                    "name": str(other.get("name") or other_id),
                    "relation_type": relation_type,
                    "confidence": round(float(relation.get("confidence", 0.0) or 0.0), 3),
                    "layer": str(relation.get("layer") or ("durable" if relation_type in DURABLE_REL_TYPES else "episodic" if relation_type in EPISODIC_REL_TYPES else "inferred")),
                    "human_text": strip_boilerplate(relation.get("human_text") or relation.get("notes") or relation.get("evidence_quote") or ""),
                    "source_link": relation_source_link(relation),
                }
            )
    rows.sort(key=lambda row: (-float(row.get("confidence", 0.0) or 0.0), str(row.get("name") or "")))
    return rows[:limit]


def _confidence_notes(entity: dict[str, Any], direct_rows: list[dict[str, Any]], events: list[dict[str, Any]]) -> list[str]:
    notes = []
    source_count = len(entity_source_links(entity))
    if source_count:
        notes.append(f"{source_count} source links present")
    if direct_rows:
        notes.append(f"{len(direct_rows)} direct links in graph")
    if events:
        notes.append(f"{len(events)} event-linked items")
    if not notes:
        notes.append("evidence sparse; treat as provisional")
    return notes[:6]


def _history_lines(entity: dict[str, Any], *, limit: int = 6) -> list[str]:
    values = entity.get("history", [])
    if not isinstance(values, list):
        values = [values] if str(values or "").strip() else []
    rows: list[str] = []
    for value in values:
        line = strip_boilerplate(value)
        if line and line not in rows:
            rows.append(line)
        if len(rows) >= limit:
            break
    if not rows and entity.get("summary"):
        rows.append(strip_boilerplate(entity.get("summary")))
    return rows[:limit]


def _object_specific_profile(entity: dict[str, Any], graph: dict[str, Any], direct_rows: list[dict[str, Any]], indirect_rows: list[dict[str, Any]], events: list[dict[str, Any]]) -> dict[str, Any]:
    kind = entity_kind(entity)
    overview = strip_boilerplate(entity.get("summary") or entity.get("notes") or "")
    history = _history_lines(entity)
    relation_texts = [
        row.get("human_text") or relation_sentence(entity.get("name", entity.get("id", "")), row.get("name", row.get("entity_id", "")), row.get("relation_type", ""))
        for row in direct_rows
        if str(row.get("layer") or "") == "durable"
        and str(row.get("relation_type") or "") != "mentions"
        and "story pair" not in normalize_text(str(row.get("human_text") or row.get("evidence_quote") or ""))
    ]
    mission: list[str] = []
    responsibilities: list[str] = []
    structure: list[str] = []
    event_timeline = [row for row in events if str(row.get("relation_type") or "") in OBJECT_EVENT_REL_TYPES]
    if kind in {"institution", "office"}:
        responsibilities = relation_texts[:6]
        structure = relation_texts[:6]
    elif kind in {"organization", "company", "media"}:
        mission = relation_texts[:6]
        structure = relation_texts[:6]
    elif kind in {"case", "law"}:
        responsibilities = relation_texts[:6]
        structure = _unique_texts([row.get("human_text") for row in indirect_rows if row.get("human_text")], limit=6)
    if not overview:
        overview = f"{entity.get('name', 'This entity')} is a {kind}."
    if kind == "office" and normalize_text(overview).endswith("is a institution"):
        overview = f"{entity.get('name', 'This office')} is a public office in Armenia's institutional system."
    if kind in {"organization", "company", "media"} and normalize_text(overview).endswith(("is a organization", "is a media", "is a company")):
        overview = f"{entity.get('name', 'This entity')} is a {kind}-type node in the graph; use sources and direct ties for its operational role."
    if kind == "office":
        holder_names = [row.get("name") for row in direct_rows if row.get("relation_type") == "holds_office_in" and row.get("entity_type") == "person"]
        institute_names = [row.get("name") for row in direct_rows if row.get("relation_type") == "holds_office_in" and row.get("entity_type") != "person"]
        office_bits = []
        if holder_names:
            office_bits.append(f"Current holder: {', '.join(holder_names[:3])}")
        if institute_names:
            office_bits.append(f"Belongs to: {', '.join(institute_names[:3])}")
        if office_bits:
            history = office_bits[:3]
            responsibilities = office_bits[:3]
            structure = office_bits[:3] if institute_names else []
    if kind in {"organization", "company", "media"} and not mission:
        tag_labels = [str(tag) for tag in entity.get("tags", []) or [] if str(tag).strip()]
        subtype = str(entity.get("subtype") or "").strip()
        descriptor = ", ".join(_unique_texts([subtype, *tag_labels], limit=4))
        if descriptor:
            mission = [f"{entity.get('name', 'This entity')} operates as {descriptor}."]
    if kind in {"institution", "office"} and not responsibilities:
        responsibilities = [f"{entity.get('name', 'This entity')} is part of the institutional layer and should be described through powers, holder, and subordination once evidence is available."]
    evidence = _dedupe_source_rows(
        [row.get("source_link") for row in direct_rows if row.get("source_link")]
        + [row.get("source_link") for row in event_timeline if row.get("source_link")]
        + entity_source_links(entity),
        limit=16,
    )
    return {
        "overview": overview,
        "history": _unique_texts(history, limit=6),
        "mission_or_functions": _unique_texts(mission, limit=6),
        "responsibilities_or_powers": _unique_texts(responsibilities, limit=6),
        "structure_or_affiliations": _unique_texts(structure, limit=6),
        "notable_events": _unique_texts([row.get("title") or row.get("summary") for row in event_timeline], limit=6),
        "related_entities": {"direct": direct_rows, "indirect": indirect_rows},
        "timeline": event_timeline[:8],
        "evidence": evidence,
        "source_links": _dedupe_source_rows(entity_source_links(entity), limit=12),
        "canonical_aliases": canonical_aliases(entity, graph),
        "confidence_notes": _confidence_notes(entity, direct_rows, event_timeline),
    }


def _person_profile(entity: dict[str, Any], graph: dict[str, Any], direct_rows: list[dict[str, Any]], indirect_rows: list[dict[str, Any]], events: list[dict[str, Any]]) -> dict[str, Any]:
    overview = strip_boilerplate(entity.get("summary") or entity.get("notes") or "")
    roles = []
    for row in direct_rows:
        if row.get("relation_type") in PERSON_REL_TYPES:
            text = row.get("human_text") or relation_sentence(entity.get("name", entity.get("id", "")), row.get("name", row.get("entity_id", "")), row.get("relation_type", ""))
            if text and text not in roles:
                roles.append(text)
    biography = _history_lines(entity, limit=4)
    for row in events[:4]:
        text = strip_boilerplate(row.get("summary") or row.get("title") or "")
        if text and text not in biography:
            biography.append(text)
    evidence = _dedupe_source_rows(
        [row.get("source_link") for row in direct_rows if row.get("source_link")]
        + [row.get("source_link") for row in events if row.get("source_link")]
        + entity_source_links(entity),
        limit=16,
    )
    return {
        "overview": overview,
        "biography": _unique_texts(biography, limit=8),
        "current_roles": _unique_texts(roles, limit=8),
        "notable_events": _unique_texts([row.get("title") or row.get("summary") for row in events[:8] if row.get("title") or row.get("summary")], limit=8),
        "network": {"direct": direct_rows, "indirect": indirect_rows},
        "timeline": events[:8],
        "evidence": evidence,
        "source_links": _dedupe_source_rows(entity_source_links(entity), limit=12),
        "canonical_aliases": canonical_aliases(entity, graph),
        "confidence_notes": _confidence_notes(entity, direct_rows, events),
    }


def build_profile(graph: dict[str, Any], entity: dict[str, Any]) -> dict[str, Any]:
    kind = entity_kind(entity)
    direct_rows = _direct_rows(graph, entity, limit=12)
    indirect_rows = _indirect_rows(graph, entity, direct_rows, limit=10)
    events = event_rows(graph, str(entity.get("id", "")).strip(), limit=8)
    if kind == "person":
        return _person_profile(entity, graph, direct_rows, indirect_rows, events)
    return _object_specific_profile(entity, graph, direct_rows, indirect_rows, events)


def _profile_source_links(profile: dict[str, Any], entity: dict[str, Any]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for key in ("source_links", "evidence", "evidence_summary"):
        values = profile.get(key, [])
        if not isinstance(values, list):
            continue
        for item in values:
            if isinstance(item, dict) and item.get("url"):
                rows.append(item)
    rows.extend(entity_source_links(entity))
    return _dedupe_source_rows(rows, limit=40)


def profile_quality(profile: dict[str, Any], entity: dict[str, Any]) -> dict[str, Any]:
    """Return coverage metadata for a graph-derived entity profile."""
    profile = profile if isinstance(profile, dict) else {}
    kind = entity_kind(entity)
    source_links = _profile_source_links(profile, entity)
    official_source_count = len(
        [
            row
            for row in source_links
            if str(row.get("source_type") or "").lower() == "official"
            or any(marker in str(row.get("domain") or "").lower() for marker in ("gov", "parliament", "president", "prime", "court"))
        ]
    )
    biography_or_history = profile.get("biography") if kind == "person" else profile.get("history")
    if not isinstance(biography_or_history, list):
        biography_or_history = [biography_or_history] if str(biography_or_history or "").strip() else []
    timeline = profile.get("timeline", []) if isinstance(profile.get("timeline", []), list) else []
    direct_network = (
        profile.get("network", {}).get("direct", [])
        if isinstance(profile.get("network", {}), dict)
        else profile.get("related_entities", {}).get("direct", [])
    )
    if not isinstance(direct_network, list):
        direct_network = []
    current_roles = (
        profile.get("current_roles")
        if kind == "person"
        else profile.get("mission_or_functions") or profile.get("current_roles_or_functions")
    )
    if not isinstance(current_roles, list):
        current_roles = [current_roles] if str(current_roles or "").strip() else []

    missing_sections: list[str] = []
    if not str(profile.get("overview") or profile.get("neutral_analytic_summary") or "").strip():
        missing_sections.append("overview")
    if not [item for item in biography_or_history if str(item or "").strip()]:
        missing_sections.append("biography_or_history")
    if not [item for item in current_roles if str(item or "").strip()]:
        missing_sections.append("current_roles_or_functions")
    if not timeline:
        missing_sections.append("timeline")
    if not direct_network:
        missing_sections.append("direct_network")
    if not source_links:
        missing_sections.append("source_links")
    if official_source_count == 0:
        missing_sections.append("official_sources")

    richness_score = 0
    richness_score += 1 if source_links else 0
    richness_score += 1 if len(source_links) >= 3 else 0
    richness_score += 1 if official_source_count else 0
    richness_score += 1 if biography_or_history else 0
    richness_score += 1 if timeline else 0
    richness_score += 1 if len(direct_network) >= 3 else 0
    coverage = "rich" if richness_score >= 5 else "medium" if richness_score >= 3 else "thin"
    return {
        "coverage": coverage,
        "source_count": len(source_links),
        "official_source_count": official_source_count,
        "last_updated": str(profile.get("last_profile_refresh") or entity.get("updated_at") or ""),
        "needs_refresh": coverage == "thin" or bool(missing_sections),
        "missing_sections": list(dict.fromkeys(missing_sections)),
    }


def _relationship_summaries(direct_rows: list[dict[str, Any]], *, limit: int = 8) -> list[dict[str, Any]]:
    summaries: list[dict[str, Any]] = []
    for row in direct_rows:
        if not isinstance(row, dict):
            continue
        summaries.append(
            {
                "entity_id": row.get("entity_id"),
                "name": row.get("name"),
                "relation_type": row.get("relation_type"),
                "relation_class": row.get("relation_class") or row.get("layer"),
                "summary": strip_boilerplate(row.get("human_text") or row.get("evidence_quote") or ""),
                "confidence": row.get("confidence"),
                "status": (row.get("provenance") or {}).get("status") if isinstance(row.get("provenance"), dict) else "",
                "source_link": row.get("source_link"),
            }
        )
        if len(summaries) >= limit:
            break
    return summaries


def entity_profile_card(graph: dict[str, Any], entity_id: str) -> dict[str, Any]:
    """Build the model-facing EntityProfileContract for a node."""
    entities = entity_index(graph)
    entity = entities.get(str(entity_id or "").strip())
    if not entity:
        return {}
    profile = entity.get("profile", {}) if isinstance(entity.get("profile", {}), dict) else {}
    if not profile:
        profile = build_profile(graph, entity)
    direct = (
        profile.get("network", {}).get("direct", [])
        if isinstance(profile.get("network", {}), dict)
        else profile.get("related_entities", {}).get("direct", [])
    )
    indirect = (
        profile.get("network", {}).get("indirect", [])
        if isinstance(profile.get("network", {}), dict)
        else profile.get("related_entities", {}).get("indirect", [])
    )
    direct = direct if isinstance(direct, list) else []
    indirect = indirect if isinstance(indirect, list) else []
    kind = entity_kind(entity)
    biography_or_history = profile.get("biography") if kind == "person" else profile.get("history")
    if not isinstance(biography_or_history, list):
        biography_or_history = [biography_or_history] if str(biography_or_history or "").strip() else []
    current_roles_or_functions = (
        profile.get("current_roles")
        if kind == "person"
        else profile.get("mission_or_functions") or profile.get("responsibilities_or_powers")
    )
    if not isinstance(current_roles_or_functions, list):
        current_roles_or_functions = [current_roles_or_functions] if str(current_roles_or_functions or "").strip() else []
    source_links = _profile_source_links(profile, entity)
    evidence_summary = []
    for item in profile.get("evidence", []) if isinstance(profile.get("evidence", []), list) else []:
        if isinstance(item, dict):
            label = str(item.get("title") or item.get("domain") or item.get("url") or "").strip()
            if label:
                evidence_summary.append(label)
        elif str(item or "").strip():
            evidence_summary.append(strip_boilerplate(str(item)))
    if not evidence_summary:
        evidence_summary = [str(row.get("title") or row.get("domain") or row.get("url")) for row in source_links[:8]]
    return {
        "id": entity_id,
        "name": entity.get("name", entity_id),
        "type": kind,
        "category": entity.get("category", ""),
        "subtype": entity.get("subtype", ""),
        "aliases": canonical_aliases(entity, graph),
        "overview": str(profile.get("overview") or profile.get("neutral_analytic_summary") or entity.get("summary") or "").strip(),
        "biography_or_history": _unique_texts([str(item) for item in biography_or_history], limit=10),
        "current_roles_or_functions": _unique_texts([str(item) for item in current_roles_or_functions], limit=10),
        "timeline": profile.get("timeline", []) if isinstance(profile.get("timeline", []), list) else [],
        "direct_network": direct[:12],
        "indirect_network": indirect[:10],
        "relationship_summaries": _relationship_summaries(direct),
        "evidence_summary": _unique_texts([str(item) for item in evidence_summary], limit=10),
        "source_links": source_links[:16],
        "profile_quality": profile_quality(profile, entity),
        "open_questions": profile_quality(profile, entity).get("missing_sections", []),
        "contract": "EntityProfileContract.v1",
    }


def graph_profile_quality(graph: dict[str, Any], *, limit: int = 200) -> dict[str, Any]:
    rows: list[dict[str, Any]] = []
    counts = {"thin": 0, "medium": 0, "rich": 0}
    for entity_id, entity in entity_index(graph).items():
        if entity_kind(entity) not in {"person", "organization", "company", "media", "institution", "party", "office"}:
            continue
        profile = entity.get("profile", {}) if isinstance(entity.get("profile", {}), dict) else {}
        if not profile:
            profile = build_profile(graph, entity)
        quality = profile_quality(profile, entity)
        counts[str(quality.get("coverage") or "thin")] = counts.get(str(quality.get("coverage") or "thin"), 0) + 1
        rows.append(
            {
                "entity_id": entity_id,
                "name": entity.get("name", entity_id),
                "type": entity_kind(entity),
                "profile_quality": quality,
            }
        )
    rows.sort(key=lambda row: ({"thin": 0, "medium": 1, "rich": 2}.get(str(row.get("profile_quality", {}).get("coverage")), 9), str(row.get("name") or "")))
    return {
        "contract": "ProfileQualityReport.v1",
        "updated_at": iso_now(),
        "counts": counts,
        "items": rows[:limit],
        "total": len(rows),
    }


def resolve_entities_scored(query: str, graph: dict[str, Any], limit: int = 5) -> list[str]:
    q = normalize_text(query)
    if not q:
        return []
    alias_index = load_entity_alias_index(graph)
    direct = resolve_entity(q, alias_index, bucket="people") or resolve_entity(q, alias_index, bucket="orgs") or resolve_entity(q, alias_index, bucket="places")
    scored: list[tuple[float, str, str]] = []
    seen: set[str] = set()
    if direct:
        entity = entity_index(graph).get(str(direct), {})
        scored.append((100.0, str(direct), str(entity.get("name", direct))))
        seen.add(str(direct))
    tokens = set(q.split())
    for entity_id, entity in entity_index(graph).items():
        if entity_id in seen:
            continue
        name = normalize_text(entity.get("name", ""))
        aliases = [normalize_text(alias) for alias in entity.get("aliases", []) or []]
        score = 0.0
        if q == name:
            score += 10.0
        if q in aliases:
            score += 9.0
        if q and q in name:
            score += 6.0
        score += 1.5 * len(tokens & set(name.split()))
        if score > 0:
            scored.append((score, entity_id, str(entity.get("name", ""))))
    scored.sort(key=lambda row: (-row[0], row[2]))
    return [entity_id for _, entity_id, _ in scored[:limit]]


def dossier_bundle(graph: dict[str, Any], entity_id: str) -> dict[str, Any]:
    entities = entity_index(graph)
    entity = entities.get(str(entity_id or "").strip())
    if not entity:
        return {}
    profile = entity.get("profile", {}) if isinstance(entity.get("profile", {}), dict) else {}
    if not profile:
        profile = build_profile(graph, entity)
    direct = profile.get("network", {}).get("direct", []) if isinstance(profile.get("network", {}), dict) else profile.get("related_entities", {}).get("direct", [])
    indirect = profile.get("network", {}).get("indirect", []) if isinstance(profile.get("network", {}), dict) else profile.get("related_entities", {}).get("indirect", [])
    card = entity_profile_card(graph, entity_id)
    return {
        "entity_id": entity_id,
        "name": entity.get("name", entity_id),
        "kind": entity_kind(entity),
        "overview": profile.get("overview", ""),
        "biography": profile.get("biography", []) if isinstance(profile.get("biography", []), list) else [],
        "history": profile.get("history", []) if isinstance(profile.get("history", []), list) else [],
        "current_roles": profile.get("current_roles", []) if isinstance(profile.get("current_roles", []), list) else [],
        "mission_or_functions": profile.get("mission_or_functions", []) if isinstance(profile.get("mission_or_functions", []), list) else [],
        "responsibilities_or_powers": profile.get("responsibilities_or_powers", []) if isinstance(profile.get("responsibilities_or_powers", []), list) else [],
        "structure_or_affiliations": profile.get("structure_or_affiliations", []) if isinstance(profile.get("structure_or_affiliations", []), list) else [],
        "notable_events": profile.get("notable_events", []) if isinstance(profile.get("notable_events", []), list) else [],
        "network": {"direct": direct[:12], "indirect": indirect[:10]},
        "timeline": profile.get("timeline", []) if isinstance(profile.get("timeline", []), list) else [],
        "evidence": profile.get("evidence", []) if isinstance(profile.get("evidence", []), list) else [],
        "source_links": profile.get("source_links", []) if isinstance(profile.get("source_links", []), list) else [],
        "canonical_aliases": profile.get("canonical_aliases", []),
        "confidence_notes": profile.get("confidence_notes", []),
        "profile_quality": card.get("profile_quality", {}),
        "entity_card": card,
    }


def contradiction_bucket(graph: dict[str, Any], entity_id: str) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for relation in entity_relations(graph, entity_id, include_events=True):
        if str(relation.get("status") or "").strip() in {"disputed", "in_court"} or str(relation.get("relation_type") or "") in {"media_claim_disputed", "watchdog_allegation"}:
            rows.append(
                {
                    "relation_id": relation.get("id"),
                    "relation_type": relation.get("relation_type"),
                    "status": relation.get("status"),
                    "summary": strip_boilerplate(relation.get("evidence_quote") or relation.get("notes") or ""),
                    "source_link": relation_source_link(relation),
                }
            )
    return rows


def source_independence_score(source_links: list[dict[str, Any]]) -> float:
    domains = []
    for row in source_links:
        if not isinstance(row, dict):
            continue
        domain = str(row.get("domain") or "").strip()
        if domain:
            domains.append(domain)
    if not domains:
        return 0.0
    unique = len(set(domains))
    return round(unique / max(1, len(domains)), 3)


def claim_hash(claim: dict[str, Any]) -> str:
    return stable_hash(
        "claim",
        str(claim.get("claim_type") or ""),
        str(claim.get("relation_type") or ""),
        str(claim.get("from") or ""),
        str(claim.get("to") or ""),
        normalize_text(str(claim.get("evidence_quote") or "")),
        normalize_text(" ".join(sorted(str(url) for url in claim.get("source_urls", []) if str(url).strip()))),
    )


def proposal_hash(proposal: dict[str, Any]) -> str:
    claim_hashes = sorted(str(claim.get("claim_hash") or claim_hash(claim)) for claim in proposal.get("claims", []) if isinstance(claim, dict))
    return stable_hash(
        "proposal",
        str(proposal.get("proposal_kind") or ""),
        str(proposal.get("story_id") or ""),
        json.dumps(claim_hashes, ensure_ascii=False, sort_keys=True),
        json.dumps(sorted(str(url) for url in proposal.get("evidence_refs", []) if str(url).strip()), ensure_ascii=False, sort_keys=True),
    )


def duplicate_claim_exists(graph: dict[str, Any], claim: dict[str, Any]) -> bool:
    c_hash = str(claim.get("claim_hash") or claim_hash(claim))
    for relation in graph.get("relations", []):
        if str(relation.get("claim_hash") or "") == c_hash:
            return True
    for event in graph.get("event_nodes", []):
        if str(event.get("claim_hash") or "") == c_hash:
            return True
    return False


def no_self_citation(source_links: list[dict[str, Any]], publication_ledger: list[dict[str, Any]] | None = None) -> bool:
    publication_ledger = publication_ledger if publication_ledger is not None else load_publication_ledger(limit=800)
    published_urls = {
        str(url).strip()
        for row in publication_ledger
        if isinstance(row, dict)
        for url in (row.get("source_links", []) or [])
        if str(url).strip()
    }
    for row in source_links:
        if not isinstance(row, dict):
            continue
        url = str(row.get("url") or "").strip()
        if url and url in published_urls:
            return False
    return True


def confidence_decay(confidence: float, days_since_checked: float, *, half_life_days: float = 60.0) -> float:
    if confidence <= 0:
        return 0.0
    decay = 0.5 ** max(0.0, days_since_checked / max(1.0, half_life_days))
    return round(confidence * decay, 3)


def novelty_gate(claim: dict[str, Any], graph: dict[str, Any]) -> bool:
    return not duplicate_claim_exists(graph, claim)


def promote_or_reject_proposal(proposal: dict[str, Any], graph: dict[str, Any]) -> str:
    if not proposal.get("claims"):
        return "rejected"
    source_links = [item for item in proposal.get("evidence_refs", []) if isinstance(item, str)]
    if source_links and not no_self_citation([source_link_record(url) for url in source_links]):
        return "disputed"
    if any(duplicate_claim_exists(graph, claim) for claim in proposal.get("claims", []) if isinstance(claim, dict)):
        return "disputed"
    if any(float(claim.get("source_independence_score", 0.0) or 0.0) < 0.5 for claim in proposal.get("claims", []) if isinstance(claim, dict)):
        return "pending"
    if any(str(claim.get("layer") or "episodic") == "durable" for claim in proposal.get("claims", []) if isinstance(claim, dict)):
        return "accepted"
    return "accepted"


def append_proposal_ledger(record: dict[str, Any]) -> None:
    append_jsonl(PROPOSAL_LEDGER_FILE, [record])


def graph_rag_context(graph: dict[str, Any], *, query: str = "", entity_ids: list[str] | None = None, story: dict[str, Any] | None = None) -> dict[str, Any]:
    entity_ids = list(dict.fromkeys([str(item).strip() for item in (entity_ids or []) if str(item).strip()]))
    if not entity_ids and story:
        entity_ids = [str(item).strip() for item in story.get("actors_detected", []) if str(item).strip()]
    dossiers = [dossier_bundle(graph, entity_id) for entity_id in entity_ids[:8]]
    entity_cards = [dossier.get("entity_card") for dossier in dossiers if isinstance(dossier, dict) and dossier.get("entity_card")]
    events = []
    if entity_ids:
        for entity_id in entity_ids[:4]:
            events.extend(event_rows(graph, entity_id, limit=4))
    if story:
        story_context = {
            "story_id": story.get("story_id"),
            "title": story.get("title"),
            "topic": story.get("topic"),
            "summary": story.get("summary"),
            "fact_check": story.get("fact_check", {}),
            "graph_worthiness": story.get("graph_worthiness", {}),
            "claim_bundles": story.get("claim_bundles", []),
        }
    else:
        story_context = {}
    contradictions = []
    for entity_id in entity_ids[:8]:
        contradictions.extend(contradiction_bucket(graph, entity_id))
    return {
        "mode": "story_centric" if story else "entity_centric",
        "query": query,
        "canonical_entities": entity_ids,
        "retrieval_contract": "RetrievalContract.v1",
        "entity_cards": entity_cards,
        "dossiers": dossiers,
        "direct_paths": [row for dossier in dossiers for row in (dossier.get("network", {}).get("direct", []) if isinstance(dossier.get("network", {}), dict) else [])][:24],
        "indirect_paths": [row for dossier in dossiers for row in (dossier.get("network", {}).get("indirect", []) if isinstance(dossier.get("network", {}), dict) else [])][:24],
        "nearby_events": events[:24],
        "contradictions": contradictions[:24],
        "provenance_bundle": {
            "source_links": [link for dossier in dossiers for link in dossier.get("source_links", [])][:24],
            "evidence": [e for dossier in dossiers for e in dossier.get("evidence", [])][:24],
        },
        "missing_evidence_flags": [
            {"entity_id": entity_id, "flag": "thin_evidence"} for entity_id, dossier in zip(entity_ids, dossiers) if not dossier.get("source_links")
        ],
        "suggested_follow_up_entities": [
            row.get("entity_id")
            for dossier in dossiers[:3]
            for row in [
                *(dossier.get("network", {}).get("direct", []) or []),
                *(dossier.get("network", {}).get("indirect", []) or []),
            ]
            if isinstance(row, dict) and row.get("entity_id")
        ][:12],
        "story_context": story_context,
    }
